name: madarsago
description: "Find the light of Deen near you."

publish_to:

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
  
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.7
  flutter_localization: ^0.3.3
  intl: ^0.20.2
  intl_phone_field: ^3.2.0
  pinput: ^5.0.2
  firebase_auth: ^6.1.1
  flutter_svg: ^2.2.1
  firebase_core: ^4.2.0
  cloud_firestore: ^6.0.3
  firebase_app_check: ^0.4.1+1
  shared_preferences: ^2.5.3
  flutter_riverpod: ^3.0.3
  shimmer: ^3.0.0
  carousel_slider: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Bold
      fonts:
        - asset: assets/fonts/Parkinsans-Bold.ttf

    - family: Regular
      fonts:
        - asset: assets/fonts/Parkinsans-Regular.ttf

    - family: TagRegular
      fonts:
        - asset: assets/fonts/JosefinSans-Regular.ttf

dependency_overrides:
  carousel_slider: ^5.1.1

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#FFFFFF"
  color_dark: "#121212"
  image: assets/logo.png
  image_dark: assets/logo_dark.png
  branding: assets/cocode.png

  fullscreen: true
  android_12:
    image: assets/logo.png
    image_dark: assets/logo_dark.png
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "#121212"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo.png"